// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EGPUC) DeepCopyInto(out *EGPUC) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EGPUC.
func (in *EGPUC) DeepCopy() *EGPUC {
	if in == nil {
		return nil
	}
	out := new(EGPUC)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EGPUC) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EGPUCList) DeepCopyInto(out *EGPUCList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EGPUC, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EGPUCList.
func (in *EGPUCList) DeepCopy() *EGPUCList {
	if in == nil {
		return nil
	}
	out := new(EGPUCList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EGPUCList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EGPUCRequest) DeepCopyInto(out *EGPUCRequest) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EGPUCRequest.
func (in *EGPUCRequest) DeepCopy() *EGPUCRequest {
	if in == nil {
		return nil
	}
	out := new(EGPUCRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EGPUCResource) DeepCopyInto(out *EGPUCResource) {
	*out = *in
	out.Requests = in.Requests
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EGPUCResource.
func (in *EGPUCResource) DeepCopy() *EGPUCResource {
	if in == nil {
		return nil
	}
	out := new(EGPUCResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EGPUCSpec) DeepCopyInto(out *EGPUCSpec) {
	*out = *in
	out.Resources = in.Resources
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EGPUCSpec.
func (in *EGPUCSpec) DeepCopy() *EGPUCSpec {
	if in == nil {
		return nil
	}
	out := new(EGPUCSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EGPUCStatus) DeepCopyInto(out *EGPUCStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EGPUCStatus.
func (in *EGPUCStatus) DeepCopy() *EGPUCStatus {
	if in == nil {
		return nil
	}
	out := new(EGPUCStatus)
	in.DeepCopyInto(out)
	return out
}
